### YamlMime:ManagedReference
items:
- uid: VsGlobal.Config
  commentId: T:VsGlobal.Config
  id: Config
  parent: VsGlobal
  children:
  - VsGlobal.Config.api
  - VsGlobal.Config.module
  - VsGlobal.Config.player
  - VsGlobal.Config.token
  langs:
  - csharp
  - vb
  name: Config
  nameWithType: Config
  fullName: VsGlobal.Config
  type: Struct
  source:
    remote:
      path: VSGlobal/NetworkConfig.cs
      branch: main
      repo: https://github.com/FatigueDev/vs_global.git
    id: Config
    path: ../VSGlobal/NetworkConfig.cs
    startLine: 7
  assemblies:
  - VSGlobal
  namespace: VsGlobal
  summary: Contains the api, player, their auth_token and module ("core").
  example: []
  syntax:
    content: public struct Config
    content.vb: Public Structure Config
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: VsGlobal.Config.api
  commentId: F:VsGlobal.Config.api
  id: api
  parent: VsGlobal.Config
  langs:
  - csharp
  - vb
  name: api
  nameWithType: Config.api
  fullName: VsGlobal.Config.api
  type: Field
  source:
    remote:
      path: VSGlobal/NetworkConfig.cs
      branch: main
      repo: https://github.com/FatigueDev/vs_global.git
    id: api
    path: ../VSGlobal/NetworkConfig.cs
    startLine: 9
  assemblies:
  - VSGlobal
  namespace: VsGlobal
  syntax:
    content: public ICoreClientAPI api
    return:
      type: Vintagestory.API.Client.ICoreClientAPI
    content.vb: Public api As ICoreClientAPI
- uid: VsGlobal.Config.player
  commentId: F:VsGlobal.Config.player
  id: player
  parent: VsGlobal.Config
  langs:
  - csharp
  - vb
  name: player
  nameWithType: Config.player
  fullName: VsGlobal.Config.player
  type: Field
  source:
    remote:
      path: VSGlobal/NetworkConfig.cs
      branch: main
      repo: https://github.com/FatigueDev/vs_global.git
    id: player
    path: ../VSGlobal/NetworkConfig.cs
    startLine: 10
  assemblies:
  - VSGlobal
  namespace: VsGlobal
  syntax:
    content: public IClientPlayer player
    return:
      type: Vintagestory.API.Client.IClientPlayer
    content.vb: Public player As IClientPlayer
- uid: VsGlobal.Config.token
  commentId: F:VsGlobal.Config.token
  id: token
  parent: VsGlobal.Config
  langs:
  - csharp
  - vb
  name: token
  nameWithType: Config.token
  fullName: VsGlobal.Config.token
  type: Field
  source:
    remote:
      path: VSGlobal/NetworkConfig.cs
      branch: main
      repo: https://github.com/FatigueDev/vs_global.git
    id: token
    path: ../VSGlobal/NetworkConfig.cs
    startLine: 11
  assemblies:
  - VSGlobal
  namespace: VsGlobal
  syntax:
    content: public Guid token
    return:
      type: System.Guid
    content.vb: Public token As Guid
- uid: VsGlobal.Config.module
  commentId: F:VsGlobal.Config.module
  id: module
  parent: VsGlobal.Config
  langs:
  - csharp
  - vb
  name: module
  nameWithType: Config.module
  fullName: VsGlobal.Config.module
  type: Field
  source:
    remote:
      path: VSGlobal/NetworkConfig.cs
      branch: main
      repo: https://github.com/FatigueDev/vs_global.git
    id: module
    path: ../VSGlobal/NetworkConfig.cs
    startLine: 12
  assemblies:
  - VSGlobal
  namespace: VsGlobal
  syntax:
    content: public string module
    return:
      type: System.String
    content.vb: Public [module] As String
references:
- uid: VsGlobal
  commentId: N:VsGlobal
  href: VsGlobal.html
  name: VsGlobal
  nameWithType: VsGlobal
  fullName: VsGlobal
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Vintagestory.API.Client.ICoreClientAPI
  commentId: T:Vintagestory.API.Client.ICoreClientAPI
  parent: Vintagestory.API.Client
  isExternal: true
  name: ICoreClientAPI
  nameWithType: ICoreClientAPI
  fullName: Vintagestory.API.Client.ICoreClientAPI
- uid: Vintagestory.API.Client
  commentId: N:Vintagestory.API.Client
  isExternal: true
  name: Vintagestory.API.Client
  nameWithType: Vintagestory.API.Client
  fullName: Vintagestory.API.Client
  spec.csharp:
  - uid: Vintagestory
    name: Vintagestory
    isExternal: true
  - name: .
  - uid: Vintagestory.API
    name: API
    isExternal: true
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    isExternal: true
  spec.vb:
  - uid: Vintagestory
    name: Vintagestory
    isExternal: true
  - name: .
  - uid: Vintagestory.API
    name: API
    isExternal: true
  - name: .
  - uid: Vintagestory.API.Client
    name: Client
    isExternal: true
- uid: Vintagestory.API.Client.IClientPlayer
  commentId: T:Vintagestory.API.Client.IClientPlayer
  parent: Vintagestory.API.Client
  isExternal: true
  name: IClientPlayer
  nameWithType: IClientPlayer
  fullName: Vintagestory.API.Client.IClientPlayer
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
